"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import {
  Send,
  Loader2,
  Sparkles,
  User,
  AlertCircle,
  MessageSquare,
  Copy,
  Check,
  ChevronDown,
  ChevronRight,
  Cpu,
  CheckCircle2,
  Search,
  PenLine,
  Palette,
  BarChart3,
  ArrowUpRight,
  Download,
  Maximize2,
  X,
  Brain,
} from "lucide-react";
import { fetchSessionMessages, sendChatMessage } from "@/lib/api";
import type { Clarification } from "@/lib/api";
import type { SessionUser } from "@/lib/session";
import { useObservability } from "@/lib/observability";
import type { ToolRun } from "@/lib/observability";
import AgentTimeline from "@/components/AgentTimeline";

const ACCENT = "#143620";

/**
 * Generate a UUID for client-only message keys and a newly-created chat
 * session. `crypto.randomUUID()` is restricted to secure contexts by some
 * browsers, while HTTP production deployments are not secure contexts.
 */
function createClientId(): string {
  if (typeof globalThis.crypto?.randomUUID === "function") {
    return globalThis.crypto.randomUUID();
  }

  const bytes = new Uint8Array(16);
  if (typeof globalThis.crypto?.getRandomValues === "function") {
    globalThis.crypto.getRandomValues(bytes);
  } else {
    // Legacy-browser fallback. Modern browsers expose getRandomValues even
    // when the page is served over HTTP.
    for (let index = 0; index < bytes.length; index += 1) {
      bytes[index] = Math.floor(Math.random() * 256);
    }
  }

  // Format the randomly generated bytes as an RFC 4122 version-4 UUID.
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/* ─────────────────────────────────────────────
   Types
   ───────────────────────────────────────────── */

type Message = {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: number;
  clarification?: Clarification;
  imageDataUrl?: string;
  traceRuns?: ToolRun[];
};

type Effort = "flash" | "mid" | "max";

type ChatProps = {
  user: SessionUser;
  initialSessionId: string | null;
  initialTitle: string | null;
  onSessionCreated: (sessionId: string, title: string) => void;
};

const markdownComponents: Components = {
  p: ({ children }) => (
    <p className="mb-3 last:mb-0 leading-relaxed">{children}</p>
  ),
  h1: ({ children }) => (
    <h1 className="mb-3 mt-1 text-base font-semibold leading-snug text-[#0f2214]">
      {children}
    </h1>
  ),
  h2: ({ children }) => (
    <h2 className="mb-2.5 mt-4 text-[15px] font-semibold leading-snug text-[#0f2214] first:mt-0">
      {children}
    </h2>
  ),
  h3: ({ children }) => (
    <h3 className="mb-2 mt-3 text-sm font-semibold leading-snug text-[#0f2214] first:mt-0">
      {children}
    </h3>
  ),
  ul: ({ children }) => (
    <ul className="mb-3 list-disc space-y-1 pl-5 last:mb-0">{children}</ul>
  ),
  ol: ({ children }) => (
    <ol className="mb-3 list-decimal space-y-1 pl-5 last:mb-0">{children}</ol>
  ),
  li: ({ children }) => <li className="pl-1 leading-relaxed">{children}</li>,
  a: ({ children, href }) => (
    <a
      href={href}
      target="_blank"
      rel="noreferrer"
      className="font-medium text-[#143620] underline decoration-[#143620]/30 underline-offset-2 hover:decoration-[#143620]"
    >
      {children}
    </a>
  ),
  blockquote: ({ children }) => (
    <blockquote className="mb-3 border-l-2 border-[#143620]/30 pl-3 text-[#3a4a3d] last:mb-0">
      {children}
    </blockquote>
  ),
  strong: ({ children }) => (
    <strong className="font-semibold text-[#0f2214]">{children}</strong>
  ),
  code: ({ children, className, ...props }) => {
    const isInline = !className?.includes("language-");
    return (
      <code
        className={
          isInline
            ? "rounded-md bg-[#f6f5ef] border border-[#e8e9e3] px-1.5 py-0.5 text-[0.85em] font-medium text-[#ef4444]"
            : className
        }
        {...props}
      >
        {children}
      </code>
    );
  },
  pre: ({ children }) => {
    // Extract text content for the copy button
    const extractText = (node: React.ReactNode): string => {
      if (typeof node === "string") return node;
      if (typeof node === "number") return String(node);
      if (Array.isArray(node)) return node.map(extractText).join("");
      if (node && typeof node === "object" && "props" in node) {
        return extractText((node as { props: { children?: React.ReactNode } }).props.children);
      }
      return "";
    };
    const codeText = extractText(children);

    return <CodeBlock code={codeText}>{children}</CodeBlock>;
  },
  table: ({ children }) => (
    <table className="mb-3 min-w-full border-collapse text-left text-[13px] last:mb-0">
      {children}
    </table>
  ),
  th: ({ children }) => (
    <th className="border border-[#e8e9e3] bg-[#fdfcf8] px-3 py-2 font-semibold text-[#0f2214]">
      {children}
    </th>
  ),
  td: ({ children }) => (
    <td className="border border-[#e8e9e3] px-3 py-2 align-top">{children}</td>
  ),
};

function MarkdownMessage({ content }: { content: string }) {
  return (
    <div className="overflow-x-auto text-sm leading-relaxed break-words text-[#2f3e32]">
      <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
        {content}
      </ReactMarkdown>
    </div>
  );
}

/* ─────────────────────────────────────────────
   Reasoning Parser & Dropdown (Claude / ChatGPT style)
   ───────────────────────────────────────────── */

interface ParsedReasoning {
  reasoning: string | null;
  answer: string;
  isThinking: boolean;
}

function parseReasoningAndContent(raw: string): ParsedReasoning {
  if (!raw) return { reasoning: null, answer: "", isThinking: false };

  // 1. Check for complete <think>...</think> tags
  const thinkRegex = /<think(?:\s[^>]*)?>([\s\S]*?)<\/think>/gi;
  const thoughts: string[] = [];
  let match: RegExpExecArray | null;
  while ((match = thinkRegex.exec(raw)) !== null) {
    if (match[1].trim()) {
      thoughts.push(match[1].trim());
    }
  }

  // 2. Check for open/unclosed <think> tag (during live streaming)
  const remaining = raw.replace(thinkRegex, "");
  const unclosedMatch = remaining.match(/<think(?:\s[^>]*)?>([\s\S]*)$/i);

  if (thoughts.length > 0 || unclosedMatch) {
    let reasoning = thoughts.join("\n\n").trim();
    let answer = remaining;
    let isThinking = false;

    if (unclosedMatch) {
      const streamPart = unclosedMatch[1].trim();
      reasoning = reasoning ? `${reasoning}\n\n${streamPart}` : streamPart;
      answer = remaining.replace(/<think(?:\s[^>]*)?>[\s\S]*$/i, "").trim();
      isThinking = true;
    } else {
      answer = answer.trim();
    }

    return {
      reasoning: reasoning || null,
      answer,
      isThinking,
    };
  }

  // 3. Fallback for <thought> or <reasoning> tags
  const altRegex = /<(thought|reasoning)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/gi;
  while ((match = altRegex.exec(raw)) !== null) {
    if (match[2].trim()) {
      thoughts.push(match[2].trim());
    }
  }
  if (thoughts.length > 0) {
    return {
      reasoning: thoughts.join("\n\n").trim(),
      answer: raw.replace(altRegex, "").trim(),
      isThinking: false,
    };
  }

  return { reasoning: null, answer: raw, isThinking: false };
}

function ReasoningDropdown({
  reasoning,
  isStreaming = false,
  isThinking = false,
}: {
  reasoning: string;
  isStreaming?: boolean;
  isThinking?: boolean;
}) {
  const [userToggled, setUserToggled] = useState(false);
  const [isOpen, setIsOpen] = useState(isThinking);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!userToggled) {
      if (isThinking) {
        setIsOpen(true);
      } else if (isStreaming) {
        setIsOpen(false);
      }
    }
  }, [isThinking, isStreaming, userToggled]);

  const handleCopyReasoning = async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      await navigator.clipboard.writeText(reasoning);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // ignore
    }
  };

  return (
    <div className="mb-3 select-text">
      {/* Claude/ChatGPT style faded dropdown trigger */}
      <button
        type="button"
        onClick={() => {
          setUserToggled(true);
          setIsOpen(!isOpen);
        }}
        className="group inline-flex items-center gap-1.5 rounded-lg border border-[rgba(15,34,20,0.08)] bg-[rgba(15,34,20,0.02)] px-2.5 py-1.5 text-[12px] font-medium text-[#68786c] transition-all hover:bg-[rgba(15,34,20,0.05)] hover:text-[#143620]"
      >
        <Brain
          className={`h-3.5 w-3.5 text-[#68786c] transition-colors group-hover:text-[#143620] ${
            isThinking ? "animate-pulse text-[#143620]" : ""
          }`}
        />
        <span className="tracking-tight">
          {isThinking ? "Thinking…" : "Thought process"}
        </span>
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.18 }}
          className="flex items-center justify-center text-[#8d9d94] group-hover:text-[#143620]"
        >
          <ChevronDown className="h-3 w-3" />
        </motion.div>
      </button>

      {/* Collapsible reasoning container */}
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.2, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="relative mt-2 rounded-xl border border-[rgba(15,34,20,0.08)] bg-[#f7f9f7]/90 p-3.5 text-xs text-[#526356] shadow-2xs backdrop-blur-xs">
              <div className="mb-2 flex items-center justify-between border-b border-[rgba(15,34,20,0.06)] pb-1.5 text-[10.5px] font-mono tracking-wider text-[#8a9b90]">
                <span className="flex items-center gap-1.5 font-semibold uppercase">
                  <span>Thinking Process</span>
                  {isThinking && (
                    <span className="inline-block h-1.5 w-1.5 animate-ping rounded-full bg-[#143620]" />
                  )}
                </span>
                <button
                  type="button"
                  onClick={handleCopyReasoning}
                  className="flex items-center gap-1 rounded px-1.5 py-0.5 text-[10px] text-[#718276] hover:bg-black/5 hover:text-[#143620] transition-colors"
                >
                  {copied ? (
                    <>
                      <Check className="h-2.5 w-2.5 text-emerald-600" />
                      <span className="text-emerald-600">Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="h-2.5 w-2.5" />
                      <span>Copy</span>
                    </>
                  )}
                </button>
              </div>
              <div className="max-h-72 overflow-y-auto pr-1 font-sans text-[12px] font-normal leading-relaxed text-[#4b5b4f] whitespace-pre-wrap selection:bg-[#d8e6db]">
                {reasoning}
                {isThinking && (
                  <span className="ml-1 inline-block h-3.5 w-[2px] animate-pulse rounded-full bg-[#143620] align-middle" />
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function GeneratedGraphicCard({
  imageDataUrl,
  content,
  timestamp,
}: {
  imageDataUrl: string;
  content?: string;
  timestamp?: number;
}) {
  const [copiedImage, setCopiedImage] = useState(false);
  const [copiedText, setCopiedText] = useState(false);
  const [isZoomed, setIsZoomed] = useState(false);

  const { reasoning, answer: cleanContent } = parseReasoningAndContent(content || "");

  useEffect(() => {
    if (!isZoomed) return;
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        setIsZoomed(false);
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [isZoomed]);

  const handleDownload = () => {
    const link = document.createElement("a");
    link.href = imageDataUrl;
    link.download = `brand-graphic-${timestamp ?? Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopyImage = async () => {
    try {
      const res = await fetch(imageDataUrl);
      const blob = await res.blob();
      if (typeof ClipboardItem !== "undefined") {
        await navigator.clipboard.write([
          new ClipboardItem({ [blob.type || "image/png"]: blob }),
        ]);
        setCopiedImage(true);
        setTimeout(() => setCopiedImage(false), 2000);
        return;
      }
    } catch {
      // Fallback
    }
    try {
      await navigator.clipboard.writeText(imageDataUrl);
      setCopiedImage(true);
      setTimeout(() => setCopiedImage(false), 2000);
    } catch {
      // ignore
    }
  };

  const handleCopyText = async () => {
    if (!cleanContent) return;
    try {
      await navigator.clipboard.writeText(cleanContent);
      setCopiedText(true);
      setTimeout(() => setCopiedText(false), 2000);
    } catch {
      // ignore
    }
  };

  return (
    <>
      <div className="group relative my-3 overflow-hidden rounded-2xl border border-[#dce3db] bg-white shadow-sm transition-all duration-300 hover:border-[#ccd7cb] hover:shadow-md">
        {/* Header Bar */}
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[rgba(15,34,20,0.06)] bg-[#fafbfa] px-4 py-3">
          <div className="flex items-center gap-2.5">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#143620] text-white shadow-2xs">
              <Sparkles className="h-3.5 w-3.5" />
            </span>
            <div className="flex items-center gap-2">
              <span className="text-[13px] font-semibold tracking-tight text-[#0f2214]">
                Brand Asset Graphic
              </span>
              <span className="rounded-full border border-[rgba(20,54,32,0.12)] bg-[#edf4ed] px-2 py-0.5 text-[10.5px] font-medium text-[#143620]">
                High-Res
              </span>
            </div>
          </div>

          {/* Action Toolbar */}
          <div className="flex items-center gap-1.5">
            <button
              type="button"
              onClick={() => setIsZoomed(true)}
              title="Preview in Lightbox"
              className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-[#dde3dc] bg-white px-2.5 text-[11.5px] font-medium text-[#3f4f43] shadow-2xs hover:border-[#c8d4c7] hover:bg-[#edf2eb] hover:text-[#143620] transition-all"
            >
              <Maximize2 className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Preview</span>
            </button>
            <button
              type="button"
              onClick={handleCopyImage}
              title="Copy image to clipboard"
              className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-[#dde3dc] bg-white px-2.5 text-[11.5px] font-medium text-[#3f4f43] shadow-2xs hover:border-[#c8d4c7] hover:bg-[#edf2eb] hover:text-[#143620] transition-all"
            >
              {copiedImage ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-600" />
                  <span className="hidden sm:inline text-emerald-600 font-medium">Copied</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  <span className="hidden sm:inline">Copy</span>
                </>
              )}
            </button>
            <button
              type="button"
              onClick={handleDownload}
              title="Download image file"
              className="inline-flex h-8 items-center gap-1.5 rounded-lg bg-[#143620] px-3 text-[11.5px] font-medium text-white shadow-2xs hover:bg-[#0c2213] active:scale-[0.98] transition-all"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download</span>
            </button>
          </div>
        </div>

        {/* Gallery Image Display Stage */}
        <div
          onClick={() => setIsZoomed(true)}
          className="group/stage relative flex cursor-zoom-in items-center justify-center overflow-hidden bg-gradient-to-b from-[#f7f9f6] via-[#f3f6f2] to-[#edf1eb] p-4 sm:p-6"
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imageDataUrl}
            alt="Generated brand graphic"
            className="max-h-[460px] w-auto max-w-full rounded-xl object-contain shadow-md shadow-black/5 transition-transform duration-300 group-hover/stage:scale-[1.015]"
          />
          <div className="pointer-events-none absolute inset-0 flex items-center justify-center bg-black/10 opacity-0 backdrop-blur-[1px] transition-opacity duration-200 group-hover/stage:opacity-100">
            <span className="inline-flex items-center gap-2 rounded-full bg-black/75 px-3.5 py-1.5 text-xs font-medium text-white shadow-lg backdrop-blur-md">
              <Maximize2 className="h-3.5 w-3.5" />
              Click to expand
            </span>
          </div>
        </div>

        {/* Integrated Marketing Copy & Rationale Section */}
        {cleanContent && (
          <div className="border-t border-[rgba(15,34,20,0.06)] bg-white p-4 sm:p-5">
            <div className="mb-3 flex items-center justify-between border-b border-[rgba(15,34,20,0.05)] pb-2.5">
              <div className="flex items-center gap-2 text-[12px] font-semibold text-[#143620]">
                <MessageSquare className="h-3.5 w-3.5 text-[#2b5837]" />
                <span>Suggested Marketing Copy & Details</span>
              </div>
              <button
                type="button"
                onClick={handleCopyText}
                className="inline-flex items-center gap-1.5 rounded-md px-2 py-1 text-[11px] font-medium text-[#5f6f63] hover:bg-[#edf2eb] hover:text-[#143620] transition-colors"
                title="Copy marketing caption and copy"
              >
                {copiedText ? (
                  <>
                    <Check className="h-3 w-3 text-emerald-600" />
                    <span className="text-emerald-600">Copied text</span>
                  </>
                ) : (
                  <>
                    <Copy className="h-3 w-3" />
                    <span>Copy copy</span>
                  </>
                )}
              </button>
            </div>

            {reasoning && <ReasoningDropdown reasoning={reasoning} />}
            <MarkdownMessage content={cleanContent} />
          </div>
        )}
      </div>

      {/* Lightbox / Zoom Modal */}
      <AnimatePresence>
        {isZoomed && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setIsZoomed(false)}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 p-4 backdrop-blur-md"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              onClick={(e) => e.stopPropagation()}
              className="relative flex max-h-[94vh] max-w-[94vw] flex-col items-center rounded-2xl border border-white/10 bg-[#111612]/90 p-3 shadow-2xl backdrop-blur-xl"
            >
              <div className="mb-3 flex w-full items-center justify-between px-2">
                <div className="flex items-center gap-2 text-xs font-semibold text-white/90">
                  <Palette className="h-4 w-4 text-[#86e29b]" />
                  <span>High-Resolution Graphic Preview</span>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleDownload}
                    className="flex h-8 items-center gap-1.5 rounded-lg bg-[#143620] px-3 text-xs font-semibold text-white shadow-md hover:bg-[#1a472a] transition-colors"
                  >
                    <Download className="h-3.5 w-3.5" />
                    Download
                  </button>
                  <button
                    type="button"
                    onClick={() => setIsZoomed(false)}
                    className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/10 text-white/90 hover:bg-white/20 transition-colors"
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>
              </div>

              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={imageDataUrl}
                alt="Full preview"
                className="max-h-[82vh] w-auto max-w-[90vw] rounded-xl object-contain shadow-2xl"
              />
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

/* ─────────────────────────────────────────────
   Assistant Message (renders reasoning dropdown if present, then markdown)
   ───────────────────────────────────────────── */

function AssistantMessage({ content }: { content: string }) {
  const { reasoning, answer } = parseReasoningAndContent(content);

  return (
    <div className="overflow-x-auto text-sm leading-relaxed break-words text-[#2f3e32]">
      {reasoning && <ReasoningDropdown reasoning={reasoning} />}
      {answer && <MarkdownMessage content={answer} />}
    </div>
  );
}

/* ─────────────────────────────────────────────
   Message footer copy button — always visible at bottom after time
   ───────────────────────────────────────────── */

function MessageCopyButton({
  content,
  variant = "assistant",
}: {
  content: string;
  variant?: "user" | "assistant";
}) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    // If copying assistant message, copy clean answer without internal <think>
    const { answer } = parseReasoningAndContent(content);
    const textToCopy = answer.trim() || content.trim();
    if (!textToCopy) return;
    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = textToCopy;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [content]);

  if (!content.trim()) return null;

  const isUser = variant === "user";

  return (
    <button
      type="button"
      onClick={handleCopy}
      aria-label={copied ? "Copied" : "Copy message"}
      className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[11px] font-medium leading-none transition-colors ${
        isUser
          ? "border-white/20 bg-white/10 text-white/80 hover:bg-white/15 hover:text-white hover:border-white/30"
          : "border-[#e8e9e3] bg-white text-[#5f6f63] hover:border-[#143620]/25 hover:bg-[#f6f5ef] hover:text-[#143620] shadow-sm"
      }`}
    >
      {copied ? (
        <Check className={`h-3 w-3 shrink-0 ${isUser ? "text-white" : "text-green-600"}`} />
      ) : (
        <Copy className="h-3 w-3 shrink-0" />
      )}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

/* ─────────────────────────────────────────────
   Code Block with Copy Button
   ───────────────────────────────────────────── */

function CodeBlock({
  code,
  children,
}: {
  code: string;
  children: React.ReactNode;
}) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const ta = document.createElement("textarea");
      ta.value = code;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [code]);

  return (
    <div className="relative my-3">
      <button
        type="button"
        onClick={handleCopy}
        className="absolute right-3 top-3 z-10 rounded-lg bg-white/10 border border-white/15 p-1.5 text-white/80 backdrop-blur-sm transition-all hover:bg-white/15 hover:text-white hover:scale-105 shadow-sm"
        aria-label={copied ? "Copied" : "Copy code"}
      >
        {copied ? (
          <Check className="h-3.5 w-3.5 text-green-400" />
        ) : (
          <Copy className="h-3.5 w-3.5" />
        )}
      </button>
      <pre className="overflow-x-auto rounded-xl bg-[#09090b] border border-[#1a4a2b] shadow-[0_8px_30px_rgb(0,0,0,0.12)] px-4 py-3.5 pr-12 text-[13px] leading-relaxed text-[#e4e4e7] font-mono">
        {children}
      </pre>
    </div>
  );
}

/* ─────────────────────────────────────────────
   MCQ Clarification Card
   ───────────────────────────────────────────── */

function McqCard({
  clarification,
  onAnswer,
  disabled,
}: {
  clarification: Clarification;
  onAnswer: (answer: string) => void;
  disabled: boolean;
}) {
  const [custom, setCustom] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const answered = clarification.answered;
  const locked = Boolean(answered) || disabled;
  const multi = Boolean(clarification.multi_select) && !answered;

  const toggleOption = (option: string) => {
    setSelected((prev) =>
      prev.includes(option) ? prev.filter((o) => o !== option) : [...prev, option],
    );
  };

  return (
    <div className="rounded-2xl border border-[#e8e9e3] bg-white p-4 shadow-sm">
      <p className="text-sm font-semibold text-[#0f2214] leading-snug">
        {clarification.question}
      </p>
      {multi && (
        <p className="mt-1 text-xs font-medium text-[#143620]">
          You can select multiple options.
        </p>
      )}

      <div className="mt-3 flex flex-col gap-2">
        {clarification.options.map((option) => {
          const isChosen = multi ? selected.includes(option) : answered === option;
          return (
            <button
              key={option}
              type="button"
              disabled={locked}
              onClick={() => (multi ? toggleOption(option) : onAnswer(option))}
              className={`rounded-xl border px-3.5 py-2.5 text-left text-sm font-medium transition-all duration-200 ${
                isChosen
                  ? "border-[#143620] bg-[#eaf0e8] text-[#143620] shadow-sm ring-1 ring-[#143620]/20"
                  : "border-[#e8e9e3] text-[#2f3e32] hover:border-[#143620]/40 hover:bg-[#fdfcf8] hover:shadow-sm hover:-translate-y-0.5 disabled:opacity-50 disabled:hover:border-[#e8e9e3] disabled:hover:bg-transparent disabled:hover:translate-y-0 disabled:hover:shadow-none"
              }`}
            >
              {option}
              {isChosen && <span className="ml-2 text-xs">✓</span>}
            </button>
          );
        })}
      </div>

      {multi && !locked && (
        <button
          type="button"
          disabled={selected.length === 0}
          onClick={() => onAnswer(selected.join(", "))}
          className="mt-3 w-full rounded-xl px-3.5 py-2 text-sm font-medium text-white disabled:opacity-40"
          style={{ background: ACCENT }}
        >
          Confirm selection{selected.length > 1 ? ` (${selected.length})` : ""}
        </button>
      )}

      {clarification.allow_custom && !answered && (
        <form
          className="mt-3 flex gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            const trimmed = custom.trim();
            if (trimmed) onAnswer(trimmed);
          }}
        >
          <input
            type="text"
            value={custom}
            onChange={(e) => setCustom(e.target.value)}
            placeholder="Or type your own answer…"
            disabled={locked}
            className="flex-1 rounded-xl border border-[#e8e9e3] px-3.5 py-2 text-sm text-[#0f2214] placeholder:text-[#8d9d94] focus:border-[#143620] focus:outline-none disabled:opacity-50"
          />
          <button
            type="submit"
            disabled={locked || !custom.trim()}
            className="rounded-xl px-3.5 py-2 text-sm font-medium text-white disabled:opacity-40"
            style={{ background: ACCENT }}
          >
            Send
          </button>
        </form>
      )}

      {answered && !clarification.options.includes(answered) && (
        <p className="mt-3 text-xs text-[#5f6f63]">
          Custom answer: <span className="font-medium text-[#0f2214]">{answered}</span>
        </p>
      )}
    </div>
  );
}



/* ─────────────────────────────────────────────
   Chat Component
   ───────────────────────────────────────────── */

export default function Chat({
  user,
  initialSessionId,
  initialTitle,
  onSessionCreated,
}: ChatProps) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const [error, setError] = useState("");
  const [sessionId, setSessionId] = useState<string | null>(initialSessionId);
  const [chatTitle, setChatTitle] = useState<string | null>(initialTitle);
  const [loadingMessages, setLoadingMessages] = useState(false);
  const [effort, setEffort] = useState<Effort>("flash");
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // WebSocket observability — one persistent connection per session
  const {
    runs,
    snapshotRuns,
    startQuery,
    waitForConnection,
    streamingText,
  } = useObservability(sessionId);


  const scrollToBottom = useCallback(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, []);

  useEffect(() => {
    scrollToBottom();
  }, [messages, streamingText, runs, scrollToBottom]);

  // Sync props into state during render (React-recommended pattern)
  const [prevProps, setPrevProps] = useState({ initialSessionId, initialTitle });
  if (
    prevProps.initialSessionId !== initialSessionId ||
    prevProps.initialTitle !== initialTitle
  ) {
    setPrevProps({ initialSessionId, initialTitle });
    setSessionId(initialSessionId);
    setChatTitle(initialTitle);
    setError("");
    if (!initialSessionId) {
      setMessages([]);
    }
  }

  useEffect(() => {
    if (!initialSessionId) return;
    // Skip refetch if we're already viewing this session with local messages
    // (e.g. right after creating it — DB lacks in-flight messages like MCQs).
    if (initialSessionId === sessionId && messages.length > 0) return;
    let cancelled = false;

    // Defer synchronous state update out of the effect body
    queueMicrotask(() => {
      if (!cancelled) setLoadingMessages(true);
    });

    fetchSessionMessages(user.id, initialSessionId)
      .then((data) => {
        if (cancelled) return;
        setMessages(
          data.messages.map((m) => {
            const base: Message = {
              id: String(m.id),
              role: m.role as "user" | "assistant",
              content: m.content,
              timestamp: m.created_at
                ? new Date(m.created_at).getTime()
                : Date.now(),
            };

            // Parse image from stored "[image: ...]" format
            const imgMatch = base.content.match(/^\[image:\s*(https?:\/\/[^\s\]]+|data:image\/[^\s\]]+)\]\n*/i);
            if (imgMatch) {
              base.imageDataUrl = imgMatch[1];
              base.content = base.content.replace(imgMatch[0], "").trim();
            } else if (m.role === "assistant") {
              const mdImgMatch = base.content.match(/!\[.*?\]\((https?:\/\/[^\s\)]+|data:image\/[^\s\)]+)\)/i);
              if (mdImgMatch) {
                base.imageDataUrl = mdImgMatch[1];
              }
            }

            // Parse MCQ clarification from stored "Options:" format
            if (m.role === "assistant" && base.content.includes("Options:")) {
              const parts = base.content.split("Options:");
              let question = (parts[0] ?? "").trim();
              const optionsStr = (parts[1] ?? "").trim();
              // Detect [multi] prefix stored by backend
              let multiSelect = false;
              if (question.startsWith("[multi]")) {
                multiSelect = true;
                question = question.slice(7).trim();
              }
              const options = optionsStr
                .split("|")
                .map((o) => o.trim())
                .filter(Boolean);
              if (question && options.length > 0) {
                base.clarification = {
                  question,
                  options,
                  allow_custom: true,
                  multi_select: multiSelect,
                };
                base.content = question;
              }
            }
            return base;
          }),
        );
      })
      .catch((err) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to load session");
        }
      })
      .finally(() => {
        if (!cancelled) setLoadingMessages(false);
      });

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialSessionId, user.id]);

  const sendToBackend = useCallback(
    async (text: string) => {
      setSending(true);
      setError("");

      // Pre-generate session ID so the WebSocket can connect before the API call
      let sid = sessionId;
      if (!sid) {
        sid = createClientId();
        setSessionId(sid);
      }

      // Reset trace for this new query + ensure WS is connected
      startQuery(sid);

      // BLOCK the POST until the WebSocket is OPEN. The backend buffers
      // events too, but awaiting here guarantees the trace starts at t=0
      // instead of racing the HTTP round-trip.
      await waitForConnection(sid);

      try {
        const response = await sendChatMessage(
          user.id,
          text,
          sid,
          effort,
        );

        // Snapshot agent trace runs so they stick to this message
        const traceRuns = snapshotRuns();

        if (response.type === "clarification_request" && response.clarification) {
          const mcqMsg: Message = {
            id: createClientId(),
            role: "assistant",
            content: "",
            timestamp: Date.now(),
            clarification: response.clarification,
            traceRuns: traceRuns.length > 0 ? traceRuns : undefined,
          };
          setMessages((prev) => [...prev, mcqMsg]);
        } else if (response.type === "image_generated" && response.image_data_url) {
          const imageMsg: Message = {
            id: createClientId(),
            role: "assistant",
            content: response.message ?? "Here is the generated graphic preview.",
            timestamp: Date.now(),
            imageDataUrl: response.image_data_url,
            traceRuns: traceRuns.length > 0 ? traceRuns : undefined,
          };
          setMessages((prev) => [...prev, imageMsg]);
        } else {
          const assistantMsg: Message = {
            id: createClientId(),
            role: "assistant",
            content: response.message ?? "",
            timestamp: Date.now(),
            traceRuns: traceRuns.length > 0 ? traceRuns : undefined,
          };
          setMessages((prev) => [...prev, assistantMsg]);
        }

        if (response.is_new_session || !sessionId) {
          // Use the backend's session_id if it differs (should match our pre-generated one)
          const finalSid = response.session_id || sid;
          if (finalSid !== sessionId) {
            setSessionId(finalSid);
          }
          const title = response.title ?? "Untitled Chat";
          setChatTitle(title);
          onSessionCreated(finalSid, title);
        }
        window.dispatchEvent(new Event("cofounder:credits-updated"));
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to get response");
        window.dispatchEvent(new Event("cofounder:credits-updated"));
      } finally {
        setSending(false);
        inputRef.current?.focus();
      }

    },
    [user.id, sessionId, onSessionCreated, effort, snapshotRuns, startQuery, waitForConnection],
  );

  const handleSend = useCallback(async () => {
    const trimmed = input.trim();
    if (!trimmed || sending) return;

    const userMsg: Message = {
      id: createClientId(),
      role: "user",
      content: trimmed,
      timestamp: Date.now(),
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    await sendToBackend(trimmed);
  }, [input, sending, sendToBackend]);

  const handleMcqAnswer = useCallback(
    async (messageId: string, _question: string, answer: string) => {
      if (sending) return;

      // Mark this MCQ as answered (locks the buttons)
      setMessages((prev) =>
        prev.map((m) =>
          m.id === messageId && m.clarification
            ? { ...m, clarification: { ...m.clarification, answered: answer } }
            : m,
        ),
      );

      const userMsg: Message = {
        id: createClientId(),
        role: "user",
        content: answer,
        timestamp: Date.now(),
      };
      setMessages((prev) => [...prev, userMsg]);

      // Send only the answer — the conversation history already contains the question.
      // A verbose wrapper like "Answering your question..." pollutes the LLM context.
      await sendToBackend(answer);
    },
    [sending, sendToBackend],
  );

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const formatTime = (ts: number) =>
    new Date(ts).toLocaleTimeString("en-US", {
      hour: "2-digit",
      minute: "2-digit",
    });

  const isEmpty = messages.length === 0 && !loadingMessages;

  return (
    <div className="flex flex-col h-[calc(100vh-8rem)]">
      {/* Header — hidden when empty; hero empty state owns the title */}
      {!isEmpty && (
        <div className="flex items-center shrink-0 pb-3">
          {chatTitle ? (
            <div className="flex items-center gap-2.5 min-w-0">
              <div className="w-8 h-8 rounded-lg bg-[#eaf0e8] flex items-center justify-center shrink-0">
                <MessageSquare className="w-4 h-4" style={{ color: ACCENT }} />
              </div>
              <span className="text-sm font-semibold text-[#0f2214] truncate">
                {chatTitle}
              </span>
            </div>
          ) : (
            <span className="text-sm font-medium text-[#8d9d94]">New conversation</span>
          )}
        </div>
      )}

      {loadingMessages && (
        <div className="flex items-center justify-center py-4">
          <Loader2 className="w-5 h-5 animate-spin" style={{ color: ACCENT }} />
        </div>
      )}

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-1 pb-4">
        {/* Empty state — editorial, landing-aligned */}
        {isEmpty && (
          <motion.div
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.55, ease: [0.22, 1, 0.36, 1] }}
            className="relative flex min-h-[62vh] flex-col items-center justify-center overflow-hidden rounded-[28px] border border-[rgba(15,34,20,0.06)] bg-white/60 px-6 py-10 text-center backdrop-blur-[1px] md:min-h-[64vh] md:px-8 md:py-12"
          >
            {/* subtle backdrop — grid + forest orbs */}
            <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden rounded-[inherit]">
              <div className="absolute inset-0 bg-grid opacity-[0.38]" />
              <div className="glow-orb -right-32 -top-28 h-[520px] w-[520px] bg-[#7cc99a]/[0.08]" />
              <div className="glow-orb -bottom-28 -left-32 h-[440px] w-[440px] bg-[#143620]/[0.06]" />
              <div className="absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-[rgba(15,34,20,0.06)] to-transparent" />
            </div>

            <h3 className="hero-serif text-[clamp(2.2rem,5.2vw,3.5rem)] leading-[0.9] tracking-[-0.04em] text-[#0f2214] [text-wrap:balance]">
              What should we
              <span className="block italic font-[400] tracking-[-0.03em] text-[#1a4a2b]">build today?</span>
            </h3>

            <div className="mt-8 grid w-full max-w-[640px] grid-cols-1 gap-3.5 sm:grid-cols-2">
              {[
                { n: "01", icon: Search, label: "Research competitors", desc: "Landscape, positioning & gaps", prompt: "Research my competitors in " },
                { n: "02", icon: PenLine, label: "Draft a strategy memo", desc: "Clear, investor-ready narrative", prompt: "Draft a strategy memo for " },
                { n: "03", icon: Palette, label: "Design Instagram post", desc: "On-brand visual + caption", prompt: "Create an Instagram post for " },
                { n: "04", icon: BarChart3, label: "Analyze sales data", desc: "Charts, EDA & executive summary", prompt: "Analyze my sales data: " },
              ].map((chip, idx) => (
                <motion.button
                  initial={{ opacity: 0, y: 14 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.07 + 0.18, duration: 0.45, ease: "easeOut" as const }}
                  key={chip.label}
                  type="button"
                  onClick={() => {
                    setInput(chip.prompt);
                    inputRef.current?.focus();
                  }}
                  className="group relative flex items-start gap-3.5 overflow-hidden rounded-2xl border border-[rgba(15,34,20,0.07)] bg-white p-[1px] text-left transition-all duration-300 hover:border-[rgba(15,34,20,0.11)] hover:shadow-[0_12px_28px_-16px_rgba(15,34,20,0.18)]"
                >
                  <span className="absolute inset-[1px] rounded-[15px] bg-white transition-colors group-hover:bg-[#fdfcf8]" />
                  <span className="relative flex w-full items-start gap-3.5 rounded-[15px] px-4 py-4">
                    <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-[rgba(15,34,20,0.07)] bg-[rgba(20,54,32,0.06)] transition-transform duration-300 group-hover:scale-[1.02]">
                      <chip.icon className="h-[18px] w-[18px] text-[#143620]" strokeWidth={1.75} />
                    </span>
                    <span className="min-w-0 flex-1">
                      <span className="flex items-center gap-1.5">
                        <span className="text-[13px] font-semibold tracking-tight text-[#0f2214]">{chip.label}</span>
                        <ArrowUpRight className="h-3 w-3 translate-y-px text-[#aab8b0] opacity-0 transition-all group-hover:translate-x-0.5 group-hover:text-[#143620] group-hover:opacity-100" />
                      </span>
                      <span className="mt-1 block text-[12px] leading-relaxed text-[#5f6f63]">{chip.desc}</span>
                    </span>
                    <span className="shrink-0 font-mono text-[10px] tracking-wide text-[#aab8b0]">{chip.n}</span>
                  </span>
                </motion.button>
              ))}
            </div>

            <p className="mt-7 font-mono text-[10px] tracking-[0.16em] uppercase text-[#8d9d94]">
              Press Enter to send · Shift + Enter for new line
            </p>
          </motion.div>
        )}

        <div className="space-y-6">
          <AnimatePresence initial={false}>
            {messages.map((msg) => (
              <motion.div
                key={msg.id}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.22 }}
                className={`flex gap-3 ${msg.role === "user" ? "justify-end" : "justify-start"}`}
              >
                {msg.role === "assistant" && (
                  <div
                    className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                    style={{ background: ACCENT }}
                  >
                    <Sparkles className="w-4 h-4 text-white" />
                  </div>
                )}

                <div
                  className={`min-w-0 ${
                    msg.role === "user"
                      ? "max-w-[75%] bg-[#0f2214] text-white rounded-[20px] rounded-tr-[4px] px-5 py-3 shadow-md shadow-black/5"
                      : "max-w-[85%] py-1.5"
                  }`}
                >
                  {msg.role === "assistant" && msg.clarification ? (
                    <McqCard
                      clarification={msg.clarification}
                      disabled={sending}
                      onAnswer={(answer) =>
                        handleMcqAnswer(
                          msg.id,
                          msg.clarification!.question,
                          answer,
                        )
                      }
                    />
                  ) : msg.role === "assistant" && msg.imageDataUrl ? (
                    <GeneratedGraphicCard
                      imageDataUrl={msg.imageDataUrl}
                      content={msg.content}
                      timestamp={msg.timestamp}
                    />
                  ) : msg.role === "assistant" ? (
                    <AssistantMessage content={msg.content} />
                  ) : (
                    <p className="text-sm leading-relaxed whitespace-pre-wrap break-words">
                      {msg.content}
                    </p>
                  )}
                  {msg.role === "assistant" && msg.traceRuns && msg.traceRuns.length > 0 && (
                    <AgentTimeline runs={msg.traceRuns} />
                  )}
                  <div
                    className={`mt-2 flex items-center gap-2 ${
                      msg.role === "user" ? "justify-end" : "justify-start"
                    }`}
                  >
                    <span
                      className={`text-[10px] font-medium ${
                        msg.role === "user" ? "text-white/50" : "text-[#8d9d94]"
                      }`}
                    >
                      {formatTime(msg.timestamp)}
                    </span>
                    {!msg.imageDataUrl && (
                      <MessageCopyButton
                        content={
                          msg.clarification?.question
                            ? msg.clarification.question
                            : msg.content
                        }
                        variant={msg.role}
                      />
                    )}
                  </div>
                </div>

                {msg.role === "user" && (
                  <div className="w-8 h-8 rounded-lg bg-[#e8e9e3] flex items-center justify-center shrink-0 mt-0.5">
                    <User className="w-4 h-4 text-[#5f6f63]" />
                  </div>
                )}
              </motion.div>
            ))}
          </AnimatePresence>

          {/* Active agent tool trace while executing */}
          <AnimatePresence>
            {sending && runs.length > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex gap-3"
              >
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                  style={{ background: ACCENT }}
                >
                  <Sparkles className="w-4 h-4 text-white" />
                </div>
                <div className="min-w-0 flex-1">
                  <AgentTimeline runs={runs} isStreaming />
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Typing indicator (when sending before tool calls appear) */}
          <AnimatePresence>
            {sending && runs.length === 0 && streamingText.length === 0 && (
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="flex gap-3"
              >
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
                  style={{ background: ACCENT }}
                >
                  <Sparkles className="w-4 h-4 text-white" />
                </div>
                <div className="flex items-center gap-1.5 py-2">
                  {[0, 150, 300].map((delay) => (
                    <span
                      key={delay}
                      className="w-1.5 h-1.5 rounded-full bg-[#143620] animate-bounce"
                      style={{ animationDelay: `${delay}ms` }}
                    />
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Live streaming response while CEO is processing */}
          <AnimatePresence>
            {sending && streamingText.length > 0 && (() => {
              const { reasoning: streamReasoning, answer: streamAnswer, isThinking: streamIsThinking } =
                parseReasoningAndContent(streamingText);

              return (
                <motion.div
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                  className="flex gap-3"
                >
                  <div
                    className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                    style={{ background: ACCENT }}
                  >
                    <Sparkles className="w-4 h-4 text-white" />
                  </div>
                  <div className="min-w-0 max-w-[85%] py-1.5 flex-1">
                    <div className="rounded-[20px] rounded-tl-[4px] border border-[#e8e9e3] bg-white px-4 py-3 shadow-sm">
                      {streamReasoning && (
                        <ReasoningDropdown
                          reasoning={streamReasoning}
                          isStreaming={true}
                          isThinking={streamIsThinking}
                        />
                      )}
                      {(streamAnswer || !streamReasoning) && (
                        <p className="text-sm leading-relaxed whitespace-pre-wrap break-words text-[#2f3e32]">
                          {streamAnswer}
                          {!streamIsThinking && (
                            <span
                              className="ml-0.5 inline-block h-3.5 w-[2px] animate-pulse rounded-full align-middle"
                              style={{ background: ACCENT }}
                            />
                          )}
                        </p>
                      )}
                    </div>
                  </div>
                </motion.div>
              );
            })()}
          </AnimatePresence>

          {/* Error */}
          <AnimatePresence>
            {error && (
              <motion.div
                initial={{ opacity: 0, y: -8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="flex items-center gap-2.5 bg-red-50 border border-red-200 rounded-xl px-4 py-3"
              >
                <AlertCircle className="w-4 h-4 text-red-500 shrink-0" />
                <p className="text-[13px] font-medium text-red-600 flex-1">{error}</p>
                <button
                  onClick={() => setError("")}
                  className="text-xs font-medium text-red-500 underline shrink-0"
                >
                  Dismiss
                </button>
              </motion.div>
            )}
          </AnimatePresence>

          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input */}
      <div className="shrink-0 pt-4 pb-2 relative z-10 before:absolute before:inset-0 before:bg-gradient-to-t before:from-[#fdfcf8] before:via-[#fdfcf8]/90 before:to-transparent before:-z-10 before:pointer-events-none">
        <div className="bg-white border border-[#e8e9e3] rounded-2xl px-4 py-2.5 flex items-center gap-3 focus-within:border-[#143620] focus-within:ring-4 focus-within:ring-[#143620]/10 transition-all shadow-[0_2px_12px_-4px_rgba(0,0,0,0.06)] hover:shadow-[0_4px_20px_-4px_rgba(0,0,0,0.08)]">
          {/* Effort dropdown */}
          <div className="relative shrink-0">
            <select
              value={effort}
              onChange={(e) => setEffort(e.target.value as Effort)}
              disabled={sending}
              className="appearance-none bg-[#fdfcf8] border border-[#e8e9e3] rounded-xl pl-3 pr-8 py-2 text-xs font-semibold text-[#2f3e32] cursor-pointer outline-none focus:border-[#143620] hover:border-[#143620]/50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <option value="flash">⚡ Flash</option>
              <option value="mid">⚖️ Mid</option>
              <option value="max">🎯 Max</option>
            </select>
            <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-[#8d9d94] pointer-events-none" />
          </div>
          <input
            ref={inputRef}
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Message your CEO agent…"
            disabled={sending}
            className="flex-1 bg-transparent text-[15px] text-[#0f2214] placeholder-[#8d9d94] outline-none py-1.5 disabled:opacity-50"
            autoFocus
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || sending}
            className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 transition-all duration-300 disabled:cursor-not-allowed disabled:opacity-60"
            style={{
              background: input.trim() && !sending ? ACCENT : "#f6f5ef",
              color: input.trim() && !sending ? "#fff" : "#8d9d94",
              boxShadow: input.trim() && !sending ? "0 4px 12px -4px rgba(20, 54, 32, 0.4)" : "none",
            }}
          >
            {sending ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Send className="w-4 h-4" />
            )}
          </button>
        </div>
        <p className="text-[11px] text-[#8d9d94] text-center mt-3">
          {effort === "flash"
            ? "Flash — instant responses, no reflections. Best for quick tasks."
            : effort === "mid"
              ? "Mid — balanced speed & quality with light review."
              : "Max — full agent pipeline with reflections. Highest quality."}
        </p>
      </div>
    </div>
  );
}
