"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import {
  Send,
  Loader2,
  Sparkles,
  User,
  AlertCircle,
  MessageSquare,
  Copy,
  Check,
  ChevronDown,
} from "lucide-react";
import { fetchSessionMessages, sendChatMessage } from "@/lib/api";
import type { Clarification } from "@/lib/api";
import type { SessionUser } from "@/lib/session";
import { useObservability } from "@/lib/observability";
import type { ToolRun } from "@/lib/observability";
import AgentTracePanel from "@/components/AgentTracePanel";

const ACCENT = "#4f46e5";

/**
 * Generate a UUID for client-only message keys and a newly-created chat
 * session. `crypto.randomUUID()` is restricted to secure contexts by some
 * browsers, while HTTP production deployments are not secure contexts.
 */
function createClientId(): string {
  if (typeof globalThis.crypto?.randomUUID === "function") {
    return globalThis.crypto.randomUUID();
  }

  const bytes = new Uint8Array(16);
  if (typeof globalThis.crypto?.getRandomValues === "function") {
    globalThis.crypto.getRandomValues(bytes);
  } else {
    // Legacy-browser fallback. Modern browsers expose getRandomValues even
    // when the page is served over HTTP.
    for (let index = 0; index < bytes.length; index += 1) {
      bytes[index] = Math.floor(Math.random() * 256);
    }
  }

  // Format the randomly generated bytes as an RFC 4122 version-4 UUID.
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/* ─────────────────────────────────────────────
   Types
   ───────────────────────────────────────────── */

type Message = {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: number;
  clarification?: Clarification;
  imageDataUrl?: string;
  traceRuns?: ToolRun[];
};

type Effort = "flash" | "mid" | "max";

type ChatProps = {
  user: SessionUser;
  initialSessionId: string | null;
  initialTitle: string | null;
  onSessionCreated: (sessionId: string, title: string) => void;
};

const markdownComponents: Components = {
  p: ({ children }) => (
    <p className="mb-3 last:mb-0 leading-relaxed">{children}</p>
  ),
  h1: ({ children }) => (
    <h1 className="mb-3 mt-1 text-base font-semibold leading-snug text-[#0a0a0a]">
      {children}
    </h1>
  ),
  h2: ({ children }) => (
    <h2 className="mb-2.5 mt-4 text-[15px] font-semibold leading-snug text-[#0a0a0a] first:mt-0">
      {children}
    </h2>
  ),
  h3: ({ children }) => (
    <h3 className="mb-2 mt-3 text-sm font-semibold leading-snug text-[#0a0a0a] first:mt-0">
      {children}
    </h3>
  ),
  ul: ({ children }) => (
    <ul className="mb-3 list-disc space-y-1 pl-5 last:mb-0">{children}</ul>
  ),
  ol: ({ children }) => (
    <ol className="mb-3 list-decimal space-y-1 pl-5 last:mb-0">{children}</ol>
  ),
  li: ({ children }) => <li className="pl-1 leading-relaxed">{children}</li>,
  a: ({ children, href }) => (
    <a
      href={href}
      target="_blank"
      rel="noreferrer"
      className="font-medium text-[#4f46e5] underline decoration-[#4f46e5]/30 underline-offset-2 hover:decoration-[#4f46e5]"
    >
      {children}
    </a>
  ),
  blockquote: ({ children }) => (
    <blockquote className="mb-3 border-l-2 border-[#4f46e5]/30 pl-3 text-[#4b5563] last:mb-0">
      {children}
    </blockquote>
  ),
  strong: ({ children }) => (
    <strong className="font-semibold text-[#0a0a0a]">{children}</strong>
  ),
  code: ({ children, className, ...props }) => {
    const isInline = !className?.includes("language-");
    return (
      <code
        className={
          isInline
            ? "rounded-md bg-[#f3f4f6] border border-[#e5e7eb] px-1.5 py-0.5 text-[0.85em] font-medium text-[#ef4444]"
            : className
        }
        {...props}
      >
        {children}
      </code>
    );
  },
  pre: ({ children }) => {
    // Extract text content for the copy button
    const extractText = (node: React.ReactNode): string => {
      if (typeof node === "string") return node;
      if (typeof node === "number") return String(node);
      if (Array.isArray(node)) return node.map(extractText).join("");
      if (node && typeof node === "object" && "props" in node) {
        return extractText((node as { props: { children?: React.ReactNode } }).props.children);
      }
      return "";
    };
    const codeText = extractText(children);

    return <CodeBlock code={codeText}>{children}</CodeBlock>;
  },
  table: ({ children }) => (
    <table className="mb-3 min-w-full border-collapse text-left text-[13px] last:mb-0">
      {children}
    </table>
  ),
  th: ({ children }) => (
    <th className="border border-[#e5e7eb] bg-[#f9fafb] px-3 py-2 font-semibold text-[#0a0a0a]">
      {children}
    </th>
  ),
  td: ({ children }) => (
    <td className="border border-[#e5e7eb] px-3 py-2 align-top">{children}</td>
  ),
};

function MarkdownMessage({ content }: { content: string }) {
  return (
    <div className="overflow-x-auto text-sm leading-relaxed break-words text-[#374151]">
      <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
        {content}
      </ReactMarkdown>
    </div>
  );
}

function GeneratedImage({ imageDataUrl }: { imageDataUrl: string }) {
  return (
    // The image is a data URL returned by our backend, not an external URL.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={imageDataUrl}
      alt="Generated graphic"
      className="mt-3 max-h-[420px] w-auto max-w-full rounded-xl border border-[#e5e7eb] bg-white object-contain"
    />
  );
}

/* ─────────────────────────────────────────────
   Assistant Message with Copy Button
   ───────────────────────────────────────────── */

function AssistantMessage({ content }: { content: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = content;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [content]);

  return (
    <div className="group relative">
      <button
        type="button"
        onClick={handleCopy}
        className="absolute -right-1 -top-1 z-10 rounded-lg p-1.5 text-[#9ca3af] opacity-0 transition-all hover:bg-[#f3f4f6] hover:text-[#4f46e5] group-hover:opacity-100"
        aria-label={copied ? "Copied" : "Copy message"}
      >
        {copied ? (
          <Check className="h-3.5 w-3.5 text-green-500" />
        ) : (
          <Copy className="h-3.5 w-3.5" />
        )}
      </button>
      <div className="overflow-x-auto text-sm leading-relaxed break-words text-[#374151]">
        <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
          {content}
        </ReactMarkdown>
      </div>
    </div>
  );
}

/* ─────────────────────────────────────────────
   Code Block with Copy Button
   ───────────────────────────────────────────── */

function CodeBlock({
  code,
  children,
}: {
  code: string;
  children: React.ReactNode;
}) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const ta = document.createElement("textarea");
      ta.value = code;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [code]);

  return (
    <div className="group relative my-3">
      <button
        type="button"
        onClick={handleCopy}
        className="absolute right-3 top-3 z-10 rounded-lg bg-white/5 border border-white/10 p-1.5 text-white/60 opacity-0 transition-all hover:bg-white/15 hover:text-white hover:scale-105 group-hover:opacity-100"
        aria-label={copied ? "Copied" : "Copy code"}
      >
        {copied ? (
          <Check className="h-3.5 w-3.5 text-green-400" />
        ) : (
          <Copy className="h-3.5 w-3.5" />
        )}
      </button>
      <pre className="overflow-x-auto rounded-xl bg-[#09090b] border border-[#27272a] shadow-[0_8px_30px_rgb(0,0,0,0.12)] px-4 py-3.5 pr-12 text-[13px] leading-relaxed text-[#e4e4e7] font-mono">
        {children}
      </pre>
    </div>
  );
}

/* ─────────────────────────────────────────────
   MCQ Clarification Card
   ───────────────────────────────────────────── */

function McqCard({
  clarification,
  onAnswer,
  disabled,
}: {
  clarification: Clarification;
  onAnswer: (answer: string) => void;
  disabled: boolean;
}) {
  const [custom, setCustom] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const answered = clarification.answered;
  const locked = Boolean(answered) || disabled;
  const multi = Boolean(clarification.multi_select) && !answered;

  const toggleOption = (option: string) => {
    setSelected((prev) =>
      prev.includes(option) ? prev.filter((o) => o !== option) : [...prev, option],
    );
  };

  return (
    <div className="rounded-2xl border border-[#e5e7eb] bg-white p-4 shadow-sm">
      <p className="text-sm font-semibold text-[#0a0a0a] leading-snug">
        {clarification.question}
      </p>
      {multi && (
        <p className="mt-1 text-xs font-medium text-[#4f46e5]">
          You can select multiple options.
        </p>
      )}

      <div className="mt-3 flex flex-col gap-2">
        {clarification.options.map((option) => {
          const isChosen = multi ? selected.includes(option) : answered === option;
          return (
            <button
              key={option}
              type="button"
              disabled={locked}
              onClick={() => (multi ? toggleOption(option) : onAnswer(option))}
              className={`rounded-xl border px-3.5 py-2.5 text-left text-sm font-medium transition-all duration-200 ${
                isChosen
                  ? "border-[#4f46e5] bg-[#eef2ff] text-[#4f46e5] shadow-sm ring-1 ring-[#4f46e5]/20"
                  : "border-[#e5e7eb] text-[#374151] hover:border-[#4f46e5]/40 hover:bg-[#fafafa] hover:shadow-sm hover:-translate-y-0.5 disabled:opacity-50 disabled:hover:border-[#e5e7eb] disabled:hover:bg-transparent disabled:hover:translate-y-0 disabled:hover:shadow-none"
              }`}
            >
              {option}
              {isChosen && <span className="ml-2 text-xs">✓</span>}
            </button>
          );
        })}
      </div>

      {multi && !locked && (
        <button
          type="button"
          disabled={selected.length === 0}
          onClick={() => onAnswer(selected.join(", "))}
          className="mt-3 w-full rounded-xl px-3.5 py-2 text-sm font-medium text-white disabled:opacity-40"
          style={{ background: ACCENT }}
        >
          Confirm selection{selected.length > 1 ? ` (${selected.length})` : ""}
        </button>
      )}

      {clarification.allow_custom && !answered && (
        <form
          className="mt-3 flex gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            const trimmed = custom.trim();
            if (trimmed) onAnswer(trimmed);
          }}
        >
          <input
            type="text"
            value={custom}
            onChange={(e) => setCustom(e.target.value)}
            placeholder="Or type your own answer…"
            disabled={locked}
            className="flex-1 rounded-xl border border-[#e5e7eb] px-3.5 py-2 text-sm text-[#0a0a0a] placeholder:text-[#9ca3af] focus:border-[#4f46e5] focus:outline-none disabled:opacity-50"
          />
          <button
            type="submit"
            disabled={locked || !custom.trim()}
            className="rounded-xl px-3.5 py-2 text-sm font-medium text-white disabled:opacity-40"
            style={{ background: ACCENT }}
          >
            Send
          </button>
        </form>
      )}

      {answered && !clarification.options.includes(answered) && (
        <p className="mt-3 text-xs text-[#6b7280]">
          Custom answer: <span className="font-medium text-[#0a0a0a]">{answered}</span>
        </p>
      )}
    </div>
  );
}

/* ─────────────────────────────────────────────
   Chat Component
   ───────────────────────────────────────────── */

export default function Chat({
  user,
  initialSessionId,
  initialTitle,
  onSessionCreated,
}: ChatProps) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const [error, setError] = useState("");
  const [sessionId, setSessionId] = useState<string | null>(initialSessionId);
  const [chatTitle, setChatTitle] = useState<string | null>(initialTitle);
  const [loadingMessages, setLoadingMessages] = useState(false);
  const [effort, setEffort] = useState<Effort>("flash");
  const [traceOpen, setTraceOpen] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // WebSocket observability — one persistent connection per session
  const {
    runs,
    snapshotRuns,
    resetRuns,
    startQuery,
    waitForConnection,
    streamingText,
    llmActive,
    connectionStatus,
    retryCount,
  } = useObservability(sessionId);

  const clearTrace = useCallback(() => {
    resetRuns();
    setTraceOpen(false);
  }, [resetRuns]);

  const scrollToBottom = useCallback(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, []);

  useEffect(() => {
    scrollToBottom();
  }, [messages, scrollToBottom]);

  // Sync props into state during render (React-recommended pattern)
  const [prevProps, setPrevProps] = useState({ initialSessionId, initialTitle });
  if (
    prevProps.initialSessionId !== initialSessionId ||
    prevProps.initialTitle !== initialTitle
  ) {
    setPrevProps({ initialSessionId, initialTitle });
    setSessionId(initialSessionId);
    setChatTitle(initialTitle);
    setError("");
    if (!initialSessionId) {
      setMessages([]);
    }
  }

  useEffect(() => {
    if (!initialSessionId) return;
    // Skip refetch if we're already viewing this session with local messages
    // (e.g. right after creating it — DB lacks in-flight messages like MCQs).
    if (initialSessionId === sessionId && messages.length > 0) return;
    let cancelled = false;

    // Defer synchronous state update out of the effect body
    queueMicrotask(() => {
      if (!cancelled) setLoadingMessages(true);
    });

    fetchSessionMessages(user.id, initialSessionId)
      .then((data) => {
        if (cancelled) return;
        setMessages(
          data.messages.map((m) => {
            const base: Message = {
              id: String(m.id),
              role: m.role as "user" | "assistant",
              content: m.content,
              timestamp: m.created_at
                ? new Date(m.created_at).getTime()
                : Date.now(),
            };
            // Parse MCQ clarification from stored "Options:" format
            if (m.role === "assistant" && m.content.includes("Options:")) {
              const parts = m.content.split("Options:");
              let question = (parts[0] ?? "").trim();
              const optionsStr = (parts[1] ?? "").trim();
              // Detect [multi] prefix stored by backend
              let multiSelect = false;
              if (question.startsWith("[multi]")) {
                multiSelect = true;
                question = question.slice(7).trim();
              }
              const options = optionsStr
                .split("|")
                .map((o) => o.trim())
                .filter(Boolean);
              if (question && options.length > 0) {
                base.clarification = {
                  question,
                  options,
                  allow_custom: true,
                  multi_select: multiSelect,
                };
                base.content = question;
              }
            }
            return base;
          }),
        );
      })
      .catch((err) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to load session");
        }
      })
      .finally(() => {
        if (!cancelled) setLoadingMessages(false);
      });

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialSessionId, user.id]);

  const sendToBackend = useCallback(
    async (text: string) => {
      setSending(true);
      setError("");
      setTraceOpen(true); // surface the trace immediately on send

      // Pre-generate session ID so the WebSocket can connect before the API call
      let sid = sessionId;
      if (!sid) {
        sid = createClientId();
        setSessionId(sid);
      }

      // Reset trace for this new query + ensure WS is connected
      startQuery(sid);

      // BLOCK the POST until the WebSocket is OPEN. The backend buffers
      // events too, but awaiting here guarantees the trace starts at t=0
      // instead of racing the HTTP round-trip.
      await waitForConnection(sid);

      try {
        const response = await sendChatMessage(
          user.id,
          text,
          sid,
          effort,
        );

        // Snapshot agent trace runs so they stick to this message
        const traceRuns = snapshotRuns();

        if (response.is_new_session || !sessionId) {
          // Use the backend's session_id if it differs (should match our pre-generated one)
          const finalSid = response.session_id || sid;
          if (finalSid !== sessionId) {
            setSessionId(finalSid);
          }
          const title = response.title ?? "Untitled Chat";
          setChatTitle(title);
          onSessionCreated(finalSid, title);
        }

        if (response.type === "clarification_request" && response.clarification) {
          const mcqMsg: Message = {
            id: createClientId(),
            role: "assistant",
            content: "",
            timestamp: Date.now(),
            clarification: response.clarification,
            traceRuns: traceRuns.length > 0 ? traceRuns : undefined,
          };
          setMessages((prev) => [...prev, mcqMsg]);
        } else if (response.type === "image_generated" && response.image_data_url) {
          const imageMsg: Message = {
            id: createClientId(),
            role: "assistant",
            content: response.message ?? "Here is the generated graphic preview.",
            timestamp: Date.now(),
            imageDataUrl: response.image_data_url,
            traceRuns: traceRuns.length > 0 ? traceRuns : undefined,
          };
          setMessages((prev) => [...prev, imageMsg]);
        } else {
          const assistantMsg: Message = {
            id: createClientId(),
            role: "assistant",
            content: response.message ?? "",
            timestamp: Date.now(),
            traceRuns: traceRuns.length > 0 ? traceRuns : undefined,
          };
          setMessages((prev) => [...prev, assistantMsg]);
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to get response");
      } finally {
        setSending(false);
        inputRef.current?.focus();
      }
    },
    [user.id, sessionId, onSessionCreated, effort, snapshotRuns, startQuery, waitForConnection],
  );

  const handleSend = useCallback(async () => {
    const trimmed = input.trim();
    if (!trimmed || sending) return;

    const userMsg: Message = {
      id: createClientId(),
      role: "user",
      content: trimmed,
      timestamp: Date.now(),
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    await sendToBackend(trimmed);
  }, [input, sending, sendToBackend]);

  const handleMcqAnswer = useCallback(
    async (messageId: string, question: string, answer: string) => {
      if (sending) return;

      // Mark this MCQ as answered (locks the buttons)
      setMessages((prev) =>
        prev.map((m) =>
          m.id === messageId && m.clarification
            ? { ...m, clarification: { ...m.clarification, answered: answer } }
            : m,
        ),
      );

      const userMsg: Message = {
        id: createClientId(),
        role: "user",
        content: answer,
        timestamp: Date.now(),
      };
      setMessages((prev) => [...prev, userMsg]);

      // Send only the answer — the conversation history already contains the question.
      // A verbose wrapper like "Answering your question..." pollutes the LLM context.
      await sendToBackend(answer);
    },
    [sending, sendToBackend],
  );

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const formatTime = (ts: number) =>
    new Date(ts).toLocaleTimeString("en-US", {
      hour: "2-digit",
      minute: "2-digit",
    });

  const isEmpty = messages.length === 0 && !loadingMessages;

  return (
    <div className="flex flex-col h-[calc(100vh-8rem)]">
      {/* Header */}
      <div className="flex items-center shrink-0 pb-3">
        {chatTitle ? (
          <div className="flex items-center gap-2.5 min-w-0">
            <div className="w-8 h-8 rounded-lg bg-[#eef2ff] flex items-center justify-center shrink-0">
              <MessageSquare className="w-4 h-4" style={{ color: ACCENT }} />
            </div>
            <span className="text-sm font-semibold text-[#0a0a0a] truncate">
              {chatTitle}
            </span>
          </div>
        ) : (
          <span className="text-sm font-medium text-[#9ca3af]">New Chat</span>
        )}
      </div>

      {loadingMessages && (
        <div className="flex items-center justify-center py-4">
          <Loader2 className="w-5 h-5 animate-spin" style={{ color: ACCENT }} />
        </div>
      )}

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-1 pb-4">
        {/* Empty state */}
        {isEmpty && (
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.4, ease: "easeOut" }} className="h-full flex flex-col items-center justify-center text-center py-10 px-4">
            <div className="w-14 h-14 rounded-2xl flex items-center justify-center mb-6 shadow-lg shadow-[#4f46e5]/20"
              style={{ background: `linear-gradient(135deg, ${ACCENT}, #818cf8)` }}>
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <h3 className="text-xl font-bold text-[#0a0a0a] tracking-tight">
              Your AI co-founder is ready
            </h3>
            <p className="mt-2 text-[15px] text-[#6b7280] max-w-md leading-relaxed">
              I delegate to a team of specialist agents — research, writing, design,
              data analysis, and marketing. Tell me what you need shipped.
            </p>

            {/* Quick-start suggestions */}
            <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 gap-3 w-full max-w-md">
              {[
                { label: "Write a marketing email", desc: "Campaigns, launches, newsletters" },
                { label: "Create an Instagram post", desc: "Captions, visuals, brand copy" },
                { label: "Analyze my sales data", desc: "EDA, charts, executive summary" },
                { label: "Research my competitors", desc: "Market landscape, positioning" },
              ].map((chip, idx) => (
                <motion.button
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.1 + 0.2 }}
                  key={chip.label}
                  type="button"
                  onClick={() => {
                    setInput(chip.label);
                    inputRef.current?.focus();
                  }}
                  className="group flex flex-col items-start gap-1 rounded-xl border border-[#e5e7eb] bg-white px-4 py-3.5 text-left transition-all duration-300 hover:border-[#4f46e5]/40 hover:shadow-[0_8px_24px_-8px_rgba(79,70,229,0.15)] hover:-translate-y-0.5"
                >
                  <span className="text-[13px] font-semibold text-[#374151] group-hover:text-[#4f46e5] transition-colors">
                    {chip.label}
                  </span>
                  <span className="text-[11px] text-[#9ca3af] leading-tight">
                    {chip.desc}
                  </span>
                </motion.button>
              ))}
            </div>
          </motion.div>
        )}

        <div className="space-y-6">
          <AnimatePresence initial={false}>
            {messages.map((msg) => (
              <motion.div
                key={msg.id}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.22 }}
                className={`flex gap-3 ${msg.role === "user" ? "justify-end" : "justify-start"}`}
              >
                {msg.role === "assistant" && (
                  <div
                    className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                    style={{ background: ACCENT }}
                  >
                    <Sparkles className="w-4 h-4 text-white" />
                  </div>
                )}

                <div
                  className={`min-w-0 ${
                    msg.role === "user"
                      ? "max-w-[75%] bg-[#0a0a0a] text-white rounded-[20px] rounded-tr-[4px] px-5 py-3 shadow-md shadow-black/5"
                      : "max-w-[85%] py-1.5"
                  }`}
                >
                  {msg.role === "assistant" && msg.clarification ? (
                    <McqCard
                      clarification={msg.clarification}
                      disabled={sending}
                      onAnswer={(answer) =>
                        handleMcqAnswer(
                          msg.id,
                          msg.clarification!.question,
                          answer,
                        )
                      }
                    />
                  ) : msg.role === "assistant" && msg.imageDataUrl ? (
                    <div className="space-y-3">
                      <MarkdownMessage content={msg.content} />
                      <GeneratedImage imageDataUrl={msg.imageDataUrl} />
                    </div>
                  ) : msg.role === "assistant" ? (
                    <AssistantMessage content={msg.content} />
                  ) : (
                    <p className="text-sm leading-relaxed whitespace-pre-wrap break-words">
                      {msg.content}
                    </p>
                  )}
                  <span
                    className={`text-[10px] mt-1.5 block font-medium ${
                      msg.role === "user" ? "text-white/50" : "text-[#9ca3af]"
                    }`}
                  >
                    {formatTime(msg.timestamp)}
                  </span>
                </div>

                {msg.role === "user" && (
                  <div className="w-8 h-8 rounded-lg bg-[#e5e7eb] flex items-center justify-center shrink-0 mt-0.5">
                    <User className="w-4 h-4 text-[#6b7280]" />
                  </div>
                )}
              </motion.div>
            ))}
          </AnimatePresence>

          {/* Typing indicator */}
          <AnimatePresence>
            {sending && (
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="flex gap-3"
              >
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
                  style={{ background: ACCENT }}
                >
                  <Sparkles className="w-4 h-4 text-white" />
                </div>
                <div className="flex items-center gap-1.5">
                  {[0, 150, 300].map((delay) => (
                    <span
                      key={delay}
                      className="w-1.5 h-1.5 rounded-full bg-[#4f46e5] animate-bounce"
                      style={{ animationDelay: `${delay}ms` }}
                    />
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Live streaming response while CEO is processing */}
          <AnimatePresence>
            {sending && llmActive && streamingText.length > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="flex gap-3"
              >
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                  style={{ background: ACCENT }}
                >
                  <Sparkles className="w-4 h-4 text-white" />
                </div>
                <div className="min-w-0 max-w-[85%] py-1.5 flex-1">
                  <div className="rounded-[20px] rounded-tl-[4px] border border-[#e5e7eb] bg-white px-4 py-3 shadow-sm">
                    <p className="text-sm leading-relaxed whitespace-pre-wrap break-words text-[#374151]">
                      {streamingText}
                      <span
                        className="ml-0.5 inline-block h-3.5 w-[2px] animate-pulse rounded-full align-middle"
                        style={{ background: ACCENT }}
                      />
                    </p>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Error */}
          <AnimatePresence>
            {error && (
              <motion.div
                initial={{ opacity: 0, y: -8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="flex items-center gap-2.5 bg-red-50 border border-red-200 rounded-xl px-4 py-3"
              >
                <AlertCircle className="w-4 h-4 text-red-500 shrink-0" />
                <p className="text-[13px] font-medium text-red-600 flex-1">{error}</p>
                <button
                  onClick={() => setError("")}
                  className="text-xs font-medium text-red-500 underline shrink-0"
                >
                  Dismiss
                </button>
              </motion.div>
            )}
          </AnimatePresence>

          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input */}
      <div className="shrink-0 pt-4 pb-2 relative z-10 before:absolute before:inset-0 before:bg-gradient-to-t before:from-[#fafafa] before:via-[#fafafa]/90 before:to-transparent before:-z-10 before:pointer-events-none">
        <div className="bg-white border border-[#e5e7eb] rounded-2xl px-4 py-2.5 flex items-center gap-3 focus-within:border-[#4f46e5] focus-within:ring-4 focus-within:ring-[#4f46e5]/10 transition-all shadow-[0_2px_12px_-4px_rgba(0,0,0,0.06)] hover:shadow-[0_4px_20px_-4px_rgba(0,0,0,0.08)]">
          {/* Effort dropdown */}
          <div className="relative shrink-0">
            <select
              value={effort}
              onChange={(e) => setEffort(e.target.value as Effort)}
              disabled={sending}
              className="appearance-none bg-[#f9fafb] border border-[#e5e7eb] rounded-xl pl-3 pr-8 py-2 text-xs font-semibold text-[#374151] cursor-pointer outline-none focus:border-[#4f46e5] hover:border-[#4f46e5]/50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <option value="flash">⚡ Flash</option>
              <option value="mid">⚖️ Mid</option>
              <option value="max">🎯 Max</option>
            </select>
            <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-[#9ca3af] pointer-events-none" />
          </div>
          <input
            ref={inputRef}
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Message your CEO agent…"
            disabled={sending}
            className="flex-1 bg-transparent text-[15px] text-[#0a0a0a] placeholder-[#9ca3af] outline-none py-1.5 disabled:opacity-50"
            autoFocus
          />
          {/* Agent trace dropdown — sits beside the chat bar */}
          <AgentTracePanel
            runs={runs}
            streamingText={streamingText}
            llmActive={llmActive}
            isStreaming={sending}
            connectionStatus={connectionStatus}
            retryCount={retryCount}
            open={traceOpen}
            onToggle={() => setTraceOpen((v) => !v)}
            onClear={clearTrace}
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || sending}
            className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 transition-all duration-300 disabled:cursor-not-allowed disabled:opacity-60"
            style={{
              background: input.trim() && !sending ? ACCENT : "#f3f4f6",
              color: input.trim() && !sending ? "#fff" : "#9ca3af",
              boxShadow: input.trim() && !sending ? "0 4px 12px -4px rgba(79, 70, 229, 0.4)" : "none",
            }}
          >
            {sending ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Send className="w-4 h-4" />
            )}
          </button>
        </div>
        <p className="text-[11px] text-[#9ca3af] text-center mt-3">
          {effort === "flash"
            ? "Flash — instant responses, no reflections. Best for quick tasks."
            : effort === "mid"
              ? "Mid — balanced speed & quality with light review."
              : "Max — full agent pipeline with reflections. Highest quality."}
        </p>
      </div>
    </div>
  );
}
