import logging

from backend.utils import get_supabase_client

logger = logging.getLogger(__name__)

client = get_supabase_client()
GENERATED_GRAPHICS_BUCKET = "genrated_buckets"


# def upload_to_cloud(company_id: int,content: bytes,file_name:str,content_type: str):
#     try:
#         client.storage.from_("company_files").upload(
#             path=f"{company_id}/{file_name}",
#             file=content,
#             file_options={"content-type": content_type,"upsert":True}
#         )
#         return {
#             "status": True,
#             "message": f"File uploaded to Cloud successfully",
#         }
#     except Exception as e:
#         return{
#             "status":False,
#             "message":str(e)
#         }

def upload_to_cloud(company_id, content, file_name, content_type):
    logger.info("upload_to_cloud called — company_id=%s, file_name=%s, content_type=%s, size=%d", company_id, file_name, content_type, len(content))
    try:
        response = client.storage.from_("company_files").upload(
            path=f"{company_id}/{file_name}",
            file=content,
            file_options={
                "content-type": content_type,
                "upsert": "true"
            }
        )
        return {
                    "status": True,
                   "message": f"File uploaded to Cloud successfully",
                 }

    except Exception as e:
        logger.exception("Failed to upload file to cloud — company_id=%s, file_name=%s", company_id, file_name)
        return {
            "status": False,
            "message": str(e)
        }


def upload_generated_graphic(company_id: int, content: bytes, file_name: str) -> str:
    """Upload an approved generated graphic and return its storage path."""
    storage_path = f"{company_id}/{file_name}"
    logger.info(
        "Uploading approved generated graphic — company_id=%s, file_name=%s, size=%d",
        company_id,
        file_name,
        len(content),
    )
    client.storage.from_(GENERATED_GRAPHICS_BUCKET).upload(
        path=storage_path,
        file=content,
        file_options={"content-type": "image/png", "upsert": "false"},
    )
    return storage_path


def delete_generated_graphic(storage_path: str) -> bool:
    """Remove a generated graphic when its metadata write fails."""
    try:
        client.storage.from_(GENERATED_GRAPHICS_BUCKET).remove(paths=[storage_path])
        return True
    except Exception:
        logger.exception("Failed to remove generated graphic at %s", storage_path)
        return False


def save_generated_graphic(company_id: int, content: bytes) -> None:
    """Persist a generated image and its metadata; clean up storage on metadata failure."""
    from uuid import uuid4

    from backend.db.insert_to_sql import add_meta_to_file

    file_name = f"generated_{uuid4()}.png"
    storage_path: str | None = None
    try:
        storage_path = upload_generated_graphic(company_id, content, file_name)
        add_meta_to_file(
            company_id=company_id,
            file_name=file_name,
            original_file_name=file_name,
            storage_path=storage_path,
            mime_type="image/png",
            bucket_name=GENERATED_GRAPHICS_BUCKET,
            description="Graphic generated by the Graphic Designer agent.",
            file_extension="png",
            file_size=len(content),
        )
        logger.info("Saved generated graphic — company_id=%s, file_name=%s", company_id, file_name)
    except Exception:
        if storage_path:
            delete_generated_graphic(storage_path)
        logger.exception("Failed to save generated graphic — company_id=%s", company_id)

def delete_from_cloud(
    company_id: int,
    file_name: str,
    bucket_name: str = "company_files",
    storage_path: str | None = None,
):
    """Delete a file from cloud storage. Returns True if deleted, False on failure."""
    try:
        client.storage.from_(bucket_name).remove(
            paths=[storage_path or f"{company_id}/{file_name}"]
        )
        logger.info(
            "File deleted from cloud — company_id=%s, bucket=%s, file_name=%s",
            company_id,
            bucket_name,
            file_name,
        )
        return True
    except Exception as e:
        logger.exception("Error deleting from cloud — company_id=%s, file_name=%s", company_id, file_name)
        return False


def download_from_cloud(
    company_id: int,
    file_name: str,
    bucket_name: str = "company_files",
    storage_path: str | None = None,
):
    """Download a file from cloud storage. Returns bytes, or None on failure."""
    try:
        data = client.storage.from_(bucket_name).download(
            path=storage_path or f"{company_id}/{file_name}"
        )
        if data:
            logger.info("File downloaded from cloud — company_id=%s, file_name=%s, size=%d", company_id, file_name, len(data))
        else:
            logger.warning("File download returned no data — company_id=%s, file_name=%s", company_id, file_name)
        return data
    except Exception as e:
        logger.exception("Error downloading from cloud — company_id=%s, file_name=%s", company_id, file_name)
        return None
