"use client";

import LegalPageShell, {
  LEGAL_LIST,
  type LegalPanel,
} from "@/components/legal/LegalPageShell";

const SECTIONS = [
  {
    id: "service",
    short: "The service",
    title: "1. The service",
    body: [
      "Co-Founder AI provides a conversational multi-agent workspace (CEO orchestrator + research, writing, marketing, data-analysis, graphic-design, memory, and title agents) over your company documents, chat history, and connected integrations.",
      "The project is proudly open source: https://github.com/karthik132007/Co_Founder — the hosted service and the repository may be governed by additional license terms in LICENSE.",
    ],
  },
  {
    id: "accounts",
    short: "Accounts",
    title: "2. Accounts and eligibility",
    body: [
      "You must provide a valid email and keep your credentials confidential. Google sign-in creates a passwordless account; an email already registered with password login cannot be silently merged (sign-in returns 409).",
      "One company profile per account via onboarding (name, description, industry, tone, optional logo). You are responsible for activity under your session, including connected Gmail, Sheets, and Instagram grants.",
      "We may suspend accounts for abuse, fraud, credential sharing at scale, or attempts to bypass rate limits, billing, or connection ownership checks (403 on company mismatch).",
    ],
  },
  {
    id: "ai-outputs",
    short: "AI outputs",
    title: "3. AI outputs — no guarantees",
    body: [
      "Agent answers are generated by third-party LLMs and web tools and may be incomplete, outdated, or hallucinated. Internal evals note groundedness as the weakest metric — always verify business, legal, financial, or medical claims before acting.",
      "Effort modes (Flash / Mid / Max) trade latency, cost, and reflection depth: Flash is fastest with 0 judge reflections; Mid/Max add 1–2 reflections. MCQ clarification cards are capped per effort (Flash 1, Mid 2, Max 3).",
      "Graphic-design outputs return a public image_url; publishing (e.g. to Instagram) requires your approval. Gmail tools are draft-only — the agent cannot send email on your behalf.",
    ],
  },
  {
    id: "credits",
    short: "Credits & payments",
    title: "4. Credits and payments",
    body: [
      "Token usage is priced per model, marked up 2x at $1 = ₹100. Multi-model requests are summed; unpriceable models are skipped.",
      "Top-ups go through Razorpay Standard Checkout with a ₹100 (10000 paise) minimum. Supported currencies: INR, USD, EUR, AED, GBP. The browser uses only the public key ID; verification (HMAC-SHA256 + authoritative order.fetch + 24h idempotency) runs server-side.",
      "Credits are consumed as agents run. Failed verifications record a failed payment-history row and grant nothing. Duplicate verify calls return the balance without double-crediting.",
      "Credits are non-transferable between companies. Refunds are handled case-by-case via payment-history status (pending | completed | failed | refunded) — contact us with order/payment IDs. Chargebacks or fraud may lead to suspension.",
    ],
  },
  {
    id: "connections",
    short: "Connected apps",
    title: "5. Connected apps",
    body: [
      "Instagram, Gmail, and Google Sheets are available; Drive, Calendar, Notion, Google Ads, and Shopify are catalog-only (coming soon).",
      "Google connectors share one OAuth grant per company with offline access and incremental scopes; disconnecting Google revokes all Google connectors at once. Instagram disconnect removes the stored long-lived token.",
      "You must have the rights to connect any mailbox, spreadsheet, or social account, and you remain responsible for content the agents read, draft, or publish through them. Google Testing-mode limits apply (100 test users, 7-day refresh expiry) until verification.",
    ],
  },
  {
    id: "acceptable-use",
    short: "Acceptable use",
    title: "6. Acceptable use",
    body: [
      "Do not: break the law; upload malware or content you lack rights to; attempt to extract others' data across company boundaries; probe, scrape, or overload the API, sandbox, or OAuth flows; submit payment fraud; or use outputs to deceive, spam, or impersonate.",
      "The e2b code sandbox executes data-analysis code in isolation — do not attempt to exfiltrate, persist, or escape it. File uploads are limited by type and size (logos: image-only, 5 MB default).",
    ],
  },
  {
    id: "liability",
    short: "Liability & changes",
    title: "7. Liability, termination, changes",
    body: [
      "The service is provided as-is without warranties. To the extent permitted by law, we are not liable for indirect or consequential losses, including decisions made from agent outputs or publishing actions you approve.",
      "You may stop using the service anytime by deleting sessions/files and disconnecting integrations; account deletion/export is handled via contact request (see Privacy Policy). We may terminate for violations of these terms.",
      "We may update these terms and the pricing engine as the product evolves; material changes will be reflected by the Last updated date below. Continued use after changes constitutes acceptance.",
    ],
  },
];

export default function TermsClient() {
  const panels: LegalPanel[] = SECTIONS.map((s, i) => ({
    id: s.id,
    num: i + 1,
    short: s.short,
    title: s.title,
    body: (
      <ul className={LEGAL_LIST}>
        {s.body.map((p) => (
          <li key={p.slice(0, 32)}>{p}</li>
        ))}
      </ul>
    ),
  }));

  return (
    <LegalPageShell
      title="Terms and Conditions"
      updated="20 September 2026"
      panels={panels}
    />
  );
}
