"use client";

import LegalPageShell, {
  LEGAL_LIST,
  type LegalPanel,
} from "@/components/legal/LegalPageShell";

const SECTIONS = [
  {
    id: "service",
    short: "The service",
    title: "1. The service",
    body: [
      "Co-Founder AI provides a conversational multi-agent workspace (CEO orchestrator + research, writing, marketing, data-analysis, graphic-design, memory, and title agents) over your company documents, chat history, and connected integrations.",
      "The project is proudly open source: https://github.com/karthik132007/Co_Founder — the hosted service and the repository may be governed by additional license terms in LICENSE.",
    ],
  },
  {
    id: "accounts",
    short: "Accounts",
    title: "2. Accounts and eligibility",
    body: [
      "You must provide a valid email and keep your credentials confidential. Google sign-in creates a passwordless account; an email already registered with password login cannot be silently merged (sign-in returns 409).",
      "One company profile per account via onboarding (name, description, industry, tone, optional logo). You are responsible for activity under your session, including connected Gmail, Sheets, Drive, Calendar, and Instagram grants.",
      "We may suspend accounts for abuse, fraud, credential sharing at scale, or attempts to bypass rate limits, billing, or connection ownership checks (403 on company mismatch).",
    ],
  },
  {
    id: "ai-outputs",
    short: "AI outputs",
    title: "3. AI outputs — no guarantees",
    body: [
      "Agent answers are generated by third-party LLMs and web tools and may be incomplete, outdated, or hallucinated. Internal evals note groundedness as the weakest metric — always verify business, legal, financial, or medical claims before acting.",
      "Effort modes (Flash / Mid / Max) trade latency, cost, and reflection depth: Flash is fastest with 0 judge reflections; Mid/Max add 1–2 reflections. MCQ clarification cards are capped per effort (Flash 1, Mid 2, Max 3).",
      "Graphic-design outputs return a public image_url; publishing (e.g. to Instagram) requires your approval. Gmail tools are draft-only — the agent cannot send email on your behalf.",
    ],
  },
  {
    id: "credits",
    short: "Credits & payments",
    title: "4. Credits and payments",
    body: [
      "Token usage is priced per model, marked up 2x at $1 = ₹100. Multi-model requests are summed; unpriceable models are skipped.",
      "Top-ups go through Razorpay Standard Checkout with a ₹100 (10000 paise) minimum. Supported currencies: INR, USD, EUR, AED, GBP. The browser uses only the public key ID; verification (HMAC-SHA256 + authoritative order.fetch + 24h idempotency) runs server-side.",
      "Credits are consumed as agents run. Failed verifications record a failed payment-history row and grant nothing. Duplicate verify calls return the balance without double-crediting.",
      "Purchased credits are non-refundable once purchased, including unused credits — see section 5. Credits are non-transferable between companies.",
    ],
  },
  {
    id: "refunds",
    short: "Refunds & payments",
    title: "5. Refunds & payment issues",
    body: [
      "Unused credits: purchased credits are non-refundable once purchased, including credits you never use. Unused credits cannot be converted back into cash or refunded. The Billing page shows pricing, the minimum top-up, and your payment history before and after each purchase so you can decide accordingly.",
      "Failed payments: payment processing is handled through Razorpay. If a payment fails for reasons related to Razorpay or the payment-processing infrastructure (bank declines, gateway errors, failed authentication), it should first be handled through Razorpay's own support and resolution channels.",
      "If a payment issue is not resolved by Razorpay, or the issue does not fall under Razorpay's responsibility, raise a support ticket from inside the app via Sidebar → Help. Payment-related issues that are not covered or resolved by Razorpay are investigated and handled by Co-Founder AI after you submit a ticket there.",
      "Debited but no credits, duplicates, and failed transactions: if money left your account but no credits arrived, if you were charged twice, or if a transaction failed midway, raise a ticket via Sidebar → Help with your order ID and payment ID (both appear in Billing → payment history). We reconcile tickets against Razorpay's authoritative records: credits are granted where verification confirms a captured payment, failed verifications grant nothing, and duplicate verifications return the balance without double-crediting.",
    ],
  },
  {
    id: "connections",
    short: "Connected apps",
    title: "6. Connected apps",
    body: [
      "Instagram, Gmail, Google Sheets, Google Drive, and Google Calendar are available; Notion, Google Ads, and Shopify are catalog-only (coming soon).",
      "Google connectors share one OAuth grant per company with offline access and incremental scopes; disconnecting Google revokes all Google connectors at once. Instagram disconnect removes the stored long-lived token.",
      "You must have the rights to connect any mailbox, spreadsheet, drive, calendar, or social account, and you remain responsible for content the agents read, draft, or publish through them. Google Testing-mode limits apply (100 test users, 7-day refresh expiry) until verification.",
    ],
  },
  {
    id: "ip",
    short: "Intellectual property",
    title: "7. Intellectual property",
    body: [
      "Your content stays yours: documents, files, prompts, company information, data imported through connected services, and anything else you upload, submit, or connect remains your property. You retain all rights in your own content.",
      "What you grant us: by using the service you give Co-Founder AI only the rights needed to operate the service — processing your content, providing the AI functionality you request, keeping the service secure and monitored, and complying with legal obligations. Nothing broader is claimed over your content.",
      "What stays ours: Co-Founder AI retains ownership of the platform itself — software, source code, architecture, UI/UX, branding, trademarks, logos, infrastructure, proprietary systems, and agent workflows — as well as rights in underlying third-party models and technology where applicable. We claim no ownership over your content.",
      "AI-generated output: text, images, and other output the agents generate for you may draw on patterns from training data and may not be unique to you; third-party rights can apply to elements within it. You are responsible for reviewing generated output and for deciding whether it is suitable — including legally — for your intended use before you rely on or publish it.",
    ],
  },
  {
    id: "acceptable-use",
    short: "Acceptable use",
    title: "8. Acceptable use",
    body: [
      "Do not: break the law; upload malware or content you lack rights to; attempt to extract others' data across company boundaries; probe, scrape, or overload the API, sandbox, or OAuth flows; submit payment fraud; or use outputs to deceive, spam, or impersonate.",
      "The e2b code sandbox executes data-analysis code in isolation — do not attempt to exfiltrate, persist, or escape it. File uploads are limited by type and size (logos: image-only, 5 MB default).",
    ],
  },
  {
    id: "availability",
    short: "Availability",
    title: "9. Service availability & third-party dependencies",
    body: [
      "Co-Founder AI runs on infrastructure and services we do not control: cloud hosting and CDN providers, database providers, AI model providers, Google APIs (Gmail, Sheets, Drive, Calendar, OAuth), Meta/Instagram APIs, Razorpay, and other third-party services. Availability of our service can be affected when any of these have issues.",
      "We do not guarantee uninterrupted or error-free availability. Third-party API changes, outages, rate limits, policy changes, or deprecations can reduce or break connected functionality (for example mail reading, publishing, or payments) until the provider side recovers or we adapt the integration.",
      "Where a disruption is on our side we work to restore service; where it sits with a third party (for instance a Razorpay outage or a Meta API deprecation), resolution depends on that provider. Payment failures follow the process in section 5.",
    ],
  },
  {
    id: "liability",
    short: "Liability & changes",
    title: "10. Liability, termination, changes",
    body: [
      "The service is provided as-is without warranties. To the extent permitted by law, we are not liable for indirect or consequential losses, including decisions made from agent outputs or publishing actions you approve.",
      "You may stop using the service anytime by deleting sessions/files and disconnecting integrations; account deletion/export is handled via contact request (see Privacy Policy). We may terminate for violations of these terms.",
      "We may update these terms and the pricing engine as the product evolves; material changes will be reflected by the Last updated date below. Continued use after changes constitutes acceptance.",
    ],
  },
];

export default function TermsClient() {
  const panels: LegalPanel[] = SECTIONS.map((s, i) => ({
    id: s.id,
    num: i + 1,
    short: s.short,
    title: s.title,
    body: (
      <ul className={LEGAL_LIST}>
        {s.body.map((p) => (
          <li key={p.slice(0, 32)}>{p}</li>
        ))}
      </ul>
    ),
  }));

  return (
    <LegalPageShell
      title="Terms and Conditions"
      updated="20 September 2026"
      panels={panels}
    />
  );
}
