-- Google connector OAuth grants (Gmail today; Sheets/Drive/Calendar later).
--
-- One row per company: a single Google consent covers every Google connector,
-- and each connector's "connected" state is derived from the `scopes` array
-- (see `GOOGLE_CONNECTOR_SCOPES` in
-- `connections/google/google_connection_manager.py`).
--
-- The refresh token is what makes an offline Gmail connection survive past the
-- one-hour access token; `access_token` is cached here (and refreshed lazily by
-- the connection manager) so agent-side tools never have to re-consent.

create table if not exists public.google_connections (
  id bigint generated by default as identity not null,
  company_id bigint not null,
  google_user_id text null,
  email text null,
  access_token text not null,
  refresh_token text null,
  scopes text[] not null default '{}',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  last_used_at timestamp with time zone null,
  expires_at timestamp with time zone null,
  constraint google_connections_pkey primary key (id),
  constraint google_connections_company_id_fkey foreign key (company_id) references companies (id) on delete cascade
) TABLESPACE pg_default;

create unique index if not exists google_connections_company_id_idx on public.google_connections using btree (company_id) TABLESPACE pg_default;
