-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: create `public.payment_history`.
--
-- Records every credit top-up / payment attempt against a company so the
-- billing page can render an invoice-style history (date, type, status, cost).
--
-- Safe to run on an existing database:
--   * `CREATE TABLE IF NOT EXISTS` — no-op if the table already exists.
--   * Only an index is added on top; nothing is dropped or rewritten.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.payment_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id bigint NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,

    amount numeric(18, 4) NOT NULL
        CHECK (amount >= 0),

    status text NOT NULL
        CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),

    payment_date timestamptz NOT NULL DEFAULT now(),

    created_at timestamptz NOT NULL DEFAULT now()
);

-- Fast lookups by company (the billing page lists history per company).
CREATE INDEX IF NOT EXISTS payment_history_company_id_idx
    ON public.payment_history (company_id, payment_date DESC);
