create table public.color_palettes (
  id bigint generated by default as identity not null,
  company_id bigint not null,
  name text not null default 'Default',
  palette jsonb not null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint color_palettes_pkey primary key (id),
  constraint color_palettes_company_id_fkey foreign key (company_id)
    references companies (id) on delete cascade
) tablespace pg_default;

-- Ensure only one active palette per company
create unique index idx_one_active_palette_per_company
  on public.color_palettes (company_id)
  where is_active = true;