create table public.companies (
  id bigint generated by default as identity not null,
  company_name text not null,
  small_description text not null,
  industry text not null,
  tone text null,
  user_id bigint not null,
  constraint companies_pkey primary key (id),
  constraint companies_user_id_fkey foreign KEY (user_id) references users (id) on delete set null
) TABLESPACE pg_default;