create table public.files (
  id bigint generated by default as identity not null,
  company_id bigint not null,
  file_name text not null,
  original_file_name text not null,
  bucket_name text not null default 'company_files'::text,
  storage_path text not null,
  description text null,
  mime_type text not null,
  file_extension text null,
  file_size bigint null,
  status text not null default 'ready'::text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint files_pkey primary key (id),
  constraint files_company_id_fkey foreign KEY (company_id) references companies (id) on delete CASCADE
) TABLESPACE pg_default;