create table public.google_connections (
  id bigint generated by default as identity not null,
  company_id bigint not null,
  google_user_id text null,
  email text null,
  access_token text not null,
  refresh_token text null,
  scopes text[] not null default '{}',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  last_used_at timestamp with time zone null,
  expires_at timestamp with time zone null,
  constraint google_connections_pkey primary key (id),
  constraint google_connections_company_id_fkey foreign KEY (company_id) references companies (id) on delete CASCADE
) TABLESPACE pg_default;

-- One Google grant per company: a single consent covers every Google
-- connector (Gmail today, Sheets/Drive/Calendar later). Per-connector
-- "connected" state is derived from the `scopes` array.
create unique INDEX IF not exists google_connections_company_id_idx on public.google_connections using btree (company_id) TABLESPACE pg_default;
