create table public.instagram_connections (
  id bigint generated by default as identity not null,
  company_id bigint not null,
  instagram_user_id text not null,
  access_token text not null,
  created_at timestamp with time zone not null default now(),
  last_used_at timestamp with time zone null,
  expires_at timestamp with time zone null,
  constraint instagram_connections_pkey primary key (id),
  constraint instagram_connections_company_id_fkey foreign KEY (company_id) references companies (id) on delete CASCADE
) TABLESPACE pg_default;

create unique INDEX IF not exists instagram_connections_company_id_idx on public.instagram_connections using btree (company_id) TABLESPACE pg_default;

create unique INDEX IF not exists instagram_connections_instagram_user_id_idx on public.instagram_connections using btree (instagram_user_id) TABLESPACE pg_default;