create table public.payment_history (
    id bigint generated by default as identity primary key,

    company_id bigint not null
        references public.companies(id)
        on delete cascade,

    amount numeric(18, 4) not null
        check (amount >= 0),

    status text not null
        check (status in ('pending', 'completed', 'failed', 'refunded')),

    payment_date timestamptz not null default now(),

    created_at timestamptz not null default now()
);
