create table public.users (
  id bigint generated by default as identity not null,
  email text not null,
  -- NULL for Google (OAuth) users — they have no password.
  password text,
  name text,
  auth_provider text not null default 'email',
  -- Supabase Auth UUID linking Google users to their Supabase identity.
  supabase_user_id uuid,
  created_at timestamptz not null default now(),
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  -- One Supabase Auth identity maps to at most one app user.
  -- Multiple NULLs are allowed (email/password users).
  constraint users_supabase_user_id_key unique (supabase_user_id)
) TABLESPACE pg_default;