create table public.users (
  id bigint generated by default as identity not null,
  email text not null,
  password text not null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email)
) TABLESPACE pg_default;